version: "3.9"
services:
  postgres:
    container_name: postgres-bot
    image: postgres
    env_file:
      - .env.db
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - botdb-data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis
    restart: unless-stopped
    command: redis-server --loglevel warning --save 20 1
    volumes:
      - redis-data:/data
  bot:
    build: ./
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  botdb-data:
  redis-data: