version: "3.9"
services:
  redis:
    image: redis
    restart: unless-stopped
    command: redis-server --loglevel warning --save 20 1
    volumes:
      - redis-data:/data
  bot:
    build: ./
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ${PWD}/bot.db:/accounting-bot/bot.db



volumes:
  redis-data: